<?php

namespace blog_cuisine\BackBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository {

    public function rechercherDernier($limit) {
        return $this->createQueryBuilder('a')
                        ->where('a.enLigne = :enabled')
                        ->setParameter('enabled', true)
                        ->addOrderBy('a.dateAjout', "DESC")
                        ->setMaxResults($limit)
                        ->getQuery();
    }

    public function rechercherTheme($limit, $theme) {
        return $this->createQueryBuilder('a')
                        ->leftJoin('a.theme', 't')
                        ->where('t.id=' . $theme)
                        ->andWhere('a.enLigne=:enabled')
                        ->setParameter('enabled', true)
                        ->setMaxResults($limit)
                        ->getQuery();
    }

    public function rechercherBarre($limit, $recherche) {
        $request = '%' . $recherche . '%';
        //var_dump($request);
        return $this->createQueryBuilder('a')
                        ->where("a.description LIKE :recherche")
                        ->orWhere("a.titre LIKE :recherche")
                        ->setParameter(':recherche', $request)
                        ->setMaxResults($limit)
                        ->getQuery()->getResult();
    }

}
