<?php

namespace blog_cuisine\BackBundle\Repository;

/**
 * RecetteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RecetteRepository extends \Doctrine\ORM\EntityRepository
{
    public function rechercherBarre($limit, $recherche) {
        $request = '%' . $recherche . '%';
        //var_dump($request);
        return $this->createQueryBuilder('a')
                        ->where("a.recette LIKE :recherche")
                        ->orWhere("a.titre LIKE :recherche")
                        ->setParameter(':recherche', $request)
                        ->setMaxResults($limit)
                        ->getQuery()->getResult();
    }
}
